/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentgradingsystemproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Cipher
 */
public class AttendanceMgmt extends javax.swing.JFrame {

    /**
     * Creates new form StudentMGMT
     */
    public AttendanceMgmt() {
        initComponents();
        DisplayAttendance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con = null;
    Statement st = null;
    ResultSet Rs = null;
    private void DisplayAttendance()
    {
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/schoolgradingsystem", "root", "root");
            st = con.createStatement();
            Rs = st.executeQuery("select * from attendance");
            att_table.setModel(DbUtils.resultSetToTableModel(Rs));
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        att_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        std_id = new javax.swing.JTextField();
        crs_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        att_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        att_date = new com.github.lgooddatepicker.components.DatePicker();
        updateBtrn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ATTENDANCE MANAGEMENT");
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cipher\\Downloads\\17306852241586787822-128(1).png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("Attendance ID");
        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        att_id.setBackground(new java.awt.Color(102, 102, 102));
        att_id.setForeground(new java.awt.Color(255, 255, 255));
        att_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                att_idActionPerformed(evt);
            }
        });

        jLabel4.setText("Student ID");
        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        std_id.setBackground(new java.awt.Color(102, 102, 102));
        std_id.setForeground(new java.awt.Color(255, 255, 255));
        std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_idActionPerformed(evt);
            }
        });

        crs_id.setBackground(new java.awt.Color(102, 102, 102));
        crs_id.setForeground(new java.awt.Color(255, 255, 255));
        crs_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crs_idActionPerformed(evt);
            }
        });

        jLabel5.setText("Course ID");
        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Attendance Date");
        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        newBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cipher\\Downloads\\3443228331679654522-24.png")); // NOI18N
        newBtn.setText("New");
        newBtn.setBackground(new java.awt.Color(102, 102, 102));
        newBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        newBtn.setForeground(new java.awt.Color(255, 255, 255));
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        saveBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cipher\\Downloads\\191919650316276581303769-24.png")); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setBackground(new java.awt.Color(102, 102, 102));
        saveBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cipher\\Downloads\\14974663671582988848-24.png")); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBackground(new java.awt.Color(102, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        att_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Attendance ID", "Student ID", " Course ID", "Attendance Date"
            }
        ));
        att_table.setBackground(new java.awt.Color(102, 102, 102));
        att_table.setDoubleBuffered(true);
        att_table.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        att_table.setForeground(new java.awt.Color(255, 255, 255));
        att_table.setGridColor(new java.awt.Color(102, 102, 102));
        att_table.setSelectionBackground(new java.awt.Color(153, 153, 153));
        att_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                att_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(att_table);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cipher\\Downloads\\18786029401541068758-32.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        att_date.setBackground(new java.awt.Color(102, 102, 102));

        updateBtrn.setBackground(new java.awt.Color(102, 102, 102));
        updateBtrn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        updateBtrn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtrn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cipher\\Downloads\\191919650316276581303769-24.png")); // NOI18N
        updateBtrn.setText("Update");
        updateBtrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtrnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(341, 341, 341)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(updateBtrn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(att_id, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(std_id))
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(crs_id, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(att_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(att_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(std_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(crs_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(att_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtrn)
                    .addComponent(deleteBtn)
                    .addComponent(saveBtn)
                    .addComponent(newBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void att_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_att_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_att_idActionPerformed

    private void std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_idActionPerformed

    private void crs_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crs_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crs_idActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
        if(att_id.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Select The Attendance to be Deleted");
        }
        else{
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/schoolgradingsystem", "root", "root");
            int Id = Integer.valueOf(att_id.getText());
            String Query = "Delete from attendance where att_id ='"+Id+"'";
            Statement Add = con.createStatement();
            Add.executeUpdate(Query);
            JOptionPane.showMessageDialog(this, "Attendance Deleted Successfully");
            DisplayAttendance();
            Reset();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "An Error Occured");
            e.printStackTrace();
        }}
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void Reset(){
        att_id.setText(null);
        std_id.setText(null);
        crs_id.setText(null);
        att_date.setText(null);
    }
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        // TODO add your handling code here:
        
        att_id.setText(null);
        std_id.setText(null);
        crs_id.setText(null);
        att_date.setText(null);
        att_id.requestFocus();
    }//GEN-LAST:event_newBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        if(
           att_id.getText().trim().isEmpty()&&
           std_id.getText().trim().isEmpty()&&
           crs_id.getText().trim().isEmpty()&&
           att_date.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "You have to fill all fields before saving!");
            }                                        
            else{
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/schoolgradingsystem", "root", "root");
            PreparedStatement add = con.prepareStatement("insert into attendance values(?,?,?,?)");
            add.setString(1, att_id.getText());
            add.setString(2, std_id.getText());
            add.setString(3, crs_id.getText());
            String temp_date = att_date.getDate().toString().trim();
            add.setString(4, temp_date);
            
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Attendance Added Successfully");
            DisplayAttendance();
            Reset();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "An Error Occured");
            e.printStackTrace();
        }}
    }//GEN-LAST:event_saveBtnActionPerformed

    private void att_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_att_tableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)att_table.getModel();
        int MyIndex = att_table.getSelectedRow();
        att_id.setText(model.getValueAt(MyIndex, 0).toString());
        std_id.setText(model.getValueAt(MyIndex, 1).toString());
        crs_id.setText(model.getValueAt(MyIndex, 2).toString());
        att_date.setText(model.getValueAt(MyIndex, 3).toString());
        
    }//GEN-LAST:event_att_tableMouseClicked

    private void updateBtrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtrnActionPerformed
        // TODO add your handling code here:
        if(
           att_id.getText().trim().isEmpty()&&
           std_id.getText().trim().isEmpty()&&
           crs_id.getText().trim().isEmpty()&&
           att_date.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "You have to fill all fields before saving!");
            }                                               
            else{
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/schoolgradingsystem", "root", "root");
            String ID = att_id.getText();
            String temp_date = att_date.getDate().toString().trim();
            String Query = "update attendance set att_id='"+att_id.getText()+"',stud_id='"+std_id.getText()+"',crse_id='"+crs_id.getText()+"',att_date='"+temp_date+"' where att_id='"+ID+"'";
            Statement Add = con.createStatement();
            Add.executeUpdate(Query);
            
            JOptionPane.showMessageDialog(this, "Attendnace Updated Successfully");
            DisplayAttendance();
            Reset();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "An Error Occured");
            e.printStackTrace();
        }}
        
    }//GEN-LAST:event_updateBtrnActionPerformed
    
   public String dateToString(Date d_date) {
    String temp_date, conv_date=null;
    temp_date = StudentGradingSystemProject.fmt.format(d_date);
    // Required format is like: May 15, 2021
    switch (temp_date.substring(3,5)) {
        case "01": conv_date="January "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;
        case "02": conv_date="February "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;        
        case "03": conv_date="March "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "04": conv_date="April "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "05": conv_date="May "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "06": conv_date="June "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "07": conv_date="July "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "08": conv_date="August "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "09": conv_date="September "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "10": conv_date="October "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "11": conv_date="November "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
        case "12": conv_date="December "+temp_date.substring(0,2)+", "+
                temp_date.substring(6,10); break;                
    }
    return conv_date;    
    }
    
    /*
    DateFormatConverter will convert the date format 
    from "May 15, 2021" to 15/05/2021
    */
    public String DateFormatConverter(String s_date) {
    String dd=null, mm=null, yyyy=null;
    int w_start=0;
    for (int i=0; i<s_date.length(); i++) {
        if(s_date.charAt(i)==' ') {
           if(mm==null) {
               mm= s_date.substring(w_start, i);
               w_start=i+1;
           } else if (dd==null) {
               dd=s_date.substring(w_start, i-1); // Do not get "," character
               w_start=i+1;
           }
       }
    }  
       yyyy=s_date.substring(w_start, s_date.length());
       return dd+"/"+mm+"/"+yyyy;    
    }
    
    public void refresh_JTable() {
        
           List attendance = StudentGradingSystemProject.attendance;
           DefaultTableModel model = (DefaultTableModel) att_table.getModel();
           Object rowData[] = new Object[4]; 
           Iterator itr = attendance.iterator();
           Attendance att;          
           model.setNumRows(0); //Remove all existing rows of JTable
           //Add every element of the List Array as a new row into JTable
           while (itr.hasNext()) {
              att = (Attendance) itr.next();
              rowData[0] = att.getAtt_id();
              rowData[1] = att.getStd_id();
              rowData[2] = att.getCrs_id();
              rowData[3] = StudentGradingSystemProject.fmt.format(att.getAtt_date().getTime());
              
              model.addRow(rowData);
           }   
          }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceMgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceMgmt().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker att_date;
    private javax.swing.JTextField att_id;
    private javax.swing.JTable att_table;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField crs_id;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField std_id;
    private javax.swing.JButton updateBtrn;
    // End of variables declaration//GEN-END:variables
}
